do:
		 iverilog.exe -o a.out mips/mips_tb.v mips/*_.v mips/alu/*_.v mips/alu/comparison_part/*_.v mips/alu/logic_part/*_.v
		 iverilog.exe -o a.out mips/alu/alu_tb.v mips/alu/*_.v mips/alu/comparison_part/*_.v mips/alu/logic_part/*_.v mips/utilities_.v
		 vvp a.out
